Get/api/articles task 4
crypticalfish86/Back-End-Northcoders-Project-Jace pull request #4
Opened 2023-01-17 13:31 UTC by crypticalfish86

Articles complete

2023-01-17 16:38 UTC, xViolaine requested changes

2023-01-17 16:38 UTC, xViolaine commented on __tests__/app.test.js
> +                expect(body[0].article_id).toEqual(7)
I would argue that this is probably not enough of a test to check that they are sorted in a descending order - have a look at jest sorted

2023-01-17 16:38 UTC, xViolaine commented on app/app.js
>  app.use(express.json())
We don't use app.use(express.json()) for anything yet, so it shouldn't be in your code yet!

2023-01-17 16:38 UTC, xViolaine commented on __tests__/app.test.js
> +            return request(app).get('/api/articles').expect(200)
its kind of redundant to have a test for this when you are also testing for this in the next tests :)

2023-01-17 16:38 UTC, xViolaine commented on app/app.js
> +})
This doesnt seem to be doing anything - it doesn't have any conditional logic and thus will hit on any request

2023-01-17 16:38 UTC, xViolaine commented on app/app.js
>  })
Generally, all error handlers should be at the bottom of the app.js

2023-01-17 16:38 UTC, xViolaine commented on app/model.js
> +        JOIN comments
Is a Join sufficient here?

2023-01-18 11:43 UTC, Hard-Luck commented on app/model.js
> +        RIGHT JOIN comments
Right join would only join the articles with comments, we want to join all articles even if they don't have comments, use LEFT JOIN

2023-01-18 12:04 UTC, merged